"""Add SMS, Banking and Website scam tables

Revision ID: 36eb31201950
Revises: ffaca50b7a1e
Create Date: 2025-09-19 23:52:36.111039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36eb31201950'
down_revision: Union[str, Sequence[str], None] = 'ffaca50b7a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banking_scams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banking_scams_id'), 'banking_scams', ['id'], unique=False)
    op.create_table('sms_scams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sms_content', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_scams_id'), 'sms_scams', ['id'], unique=False)
    op.create_table('website_scams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_scams_id'), 'website_scams', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_scams_id'), table_name='website_scams')
    op.drop_table('website_scams')
    op.drop_index(op.f('ix_sms_scams_id'), table_name='sms_scams')
    op.drop_table('sms_scams')
    op.drop_index(op.f('ix_banking_scams_id'), table_name='banking_scams')
    op.drop_table('banking_scams')
    # ### end Alembic commands ###
