"""Add phone headings table and user relationships

Revision ID: ffaca50b7a1e
Revises: 2cbf396a1b06
Create Date: 2025-09-19 17:49:24.557579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffaca50b7a1e'
down_revision: Union[str, Sequence[str], None] = '2cbf396a1b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('heading_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'phone_headings', ['heading_id'], ['id'])
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'heading_id')
    # ### end Alembic commands ###
