name: Build AI-Enabled Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'requirements*.txt'
      - 'Dockerfile.include-model'
      - '.github/workflows/docker-build-ai.yml'
  workflow_dispatch:  # Manual trigger
    inputs:
      dockerfile:
        description: 'Dockerfile to use'
        required: false
        default: 'Dockerfile.ai-optimized'
        type: choice
        options:
          - 'Dockerfile.ai-optimized'
          - 'Dockerfile.multistage'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Increased timeout for model download
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix=sha-
          type=raw,value=latest-ai,enable={{is_default_branch}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.include-model
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1
          
    - name: Build summary
      run: |
        echo "## 🚀 AI-Enabled Docker Image Built Successfully" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-ai\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Features**: Full AI functionality included" >> $GITHUB_STEP_SUMMARY
        echo "- **Model**: PhoBERT SMS classifier (518MB)" >> $GITHUB_STEP_SUMMARY
        echo "- **Build time**: ~8-12 minutes" >> $GITHUB_STEP_SUMMARY
        echo "- **Ready for**: Production deployment with AI" >> $GITHUB_STEP_SUMMARY
